<script setup>
import { ref, computed, onMounted, onUnmounted, watch } from 'vue'
import ReviewForm from './ReviewForm.vue'
import CloudPhotoSettings from './CloudPhotoSettings.vue'
import AssetSelection from './AssetSelection.vue'
import M1Review from './M1Review.vue'
import MediaWorkbench from './MediaWorkbench.vue'
const projects=ref([]), project=ref(null), tab=ref('assets'), selected=ref(''), error=ref(''), notice=ref(''), logged=ref(false), token=ref(''), name=ref(''), busy=ref(false), settings=ref(null), jobs=ref([]), report=ref(null), snapshot=ref(null)
const display=ref(''), reading=ref(''), checksText=ref(''), reviewNote=ref(''), listenNote=ref(''), overridesText=ref('{}'), configText=ref('{}'), importText=ref(''), chosen=ref([]), dirty=ref(false), saving=ref(false)
const rights=ref(''), teacher=ref(''), selections=ref({photo:'{"box":[0,0,100,100]}',video:'{"start":0,"end":5}',reference_audio:'{"start":0,"end":7.5,"transcript":""}'})
const scene=computed(()=>project.value?.scenes.find(s=>s.id===selected.value))
const version=computed(()=>scene.value?.versions.find(v=>v.id===scene.value.current_version))
watch(()=>[project.value?.id,tab.value,selected.value],([id,view,sid])=>{if(id)sessionStorage.setItem('mooc-workbench',JSON.stringify({id,tab:view,selected:sid}));else sessionStorage.removeItem('mooc-workbench')})
const slide=computed(()=>project.value?.slides.find(s=>s.source_page_id===scene.value?.play_page_id))
const roleNames={pptx:'课程课件',reference_audio:'参考语音',photo:'教师照片',video:'教师视频'}
const labels={waiting_ai_rate_limit:"服务限流，等待后重试",editing:'制作中',content_ready:'内容就绪',queued:'等待处理',running:'处理中',completed:'已完成',failed:'失败',ready:'已就绪',manual:'教师编写',ai:'AI 草稿',notes:'备注原文',external:'外部稿',rollback:'恢复版本',intro:'导入',lecture:'讲解',transition:'过渡',summary:'总结',asset:'素材处理',derive:'片段选取',audition:'语音试听',starting:'开始处理',generating_ai_draft:'AI 正在生成讲稿',tts_native_generation:'真实语音合成',validating_current_revision:'核对当前版本',parsing_structure:'解析课件',rendering_original_pages:'渲染原页',validating_format_and_decode:'校验素材',interrupted:'服务中断'}
const zh=k=>labels[k]||k
Object.assign(labels,{understanding_slide:'理解课件原页',generating_narration:'生成中文正文',deriving_reading:'整理读法与对应',generating_teaching_checks:'生成教学核查',teaching:'教学核查',recovering:'恢复保存步骤'})
const checks=ref({knowledge_points:[],questions:[],terms:[],pending:[]}),checksDirty=ref(false)
const listenChecks=ref({timbre:false,pronunciation:false,no_omission:false,no_repetition:false})
const courseProjects=computed(()=>projects.value.filter(p=>p.category!=='development'))
const devProjects=computed(()=>projects.value.filter(p=>p.category==='development'))
const activeScenes=computed(()=>project.value?.scenes.filter(s=>!s.skipped)||[])
const showSkipped=ref(false)
const visibleScenes=computed(()=>project.value?.scenes.filter(s=>showSkipped.value||!s.skipped)||[])
const questionCount=computed(()=>new Set(activeScenes.value.flatMap(s=>s.versions.find(v=>v.id===s.current_version)?.checks.questions.map(q=>q.question.trim())||[])).size)
const latestAI=computed(()=>{const map=new Map();for(const j of jobs.value)if(j.kind==='ai'&&!map.has(j.payload.scene_id))map.set(j.payload.scene_id,j);return [...map.values()]})
const aiCounts=computed(()=>Object.fromEntries(['queued','running','completed','failed'].map(k=>[k,latestAI.value.filter(j=>j.state===k).length])))
const candidate=computed(()=>scene.value?.versions.find(v=>v.id===scene.value.ai_candidate))
function addQuestion(){checks.value.questions.push({question:'',answer:'',source_page_id:scene.value.source_page_ids[0]});checksDirty.value=true}
async function saveChecks(){await act(async()=>{await flushSave();loadEditor();notice.value='核查草稿已保存，仍待教师确认'})}
async function retryTeaching(){await act(async()=>{await flushSave();await api(`/projects/${project.value.id}/scenes/${scene.value.id}/teaching-check`,{method:'POST',body:JSON.stringify({revision:project.value.revision})});await refreshJobs();notice.value='仅教学核查已重新排队，已保存讲稿保留'})}
async function batchAI(retry=false){await act(async()=>{await flushSave();await api(`/projects/${project.value.id}/ai-batches`,{method:'POST',body:JSON.stringify({revision:project.value.revision,retry_failed:retry})});await refreshJobs();notice.value=retry?'失败页已重新排队':'当前课时逐页讲稿已排队；已有人工稿保留为当前版本'})}
async function preview(){await act(async()=>{await flushSave();await api(`/projects/${project.value.id}/scenes/${scene.value.id}/audition`,{method:'POST',body:JSON.stringify({revision:project.value.revision,draft_preview:true})});await refreshJobs()})}
async function applyReviewedTerms(){await act(async()=>{await flushSave();const terms=Object.fromEntries(checks.value.terms.map(t=>[t.text,t.reading]));await command('page_config',{scene_ids:[scene.value.id],overrides:{terms}});loadEditor();notice.value='当前页已应用核查读法，请核对实际朗读文本并重新试听'})}
const pageForm=computed(()=>{try{return {...scene.value?.effective_config,...JSON.parse(overridesText.value)}}catch{return scene.value?.effective_config||{}}})
function overrideField(key,value){const fields=JSON.parse(overridesText.value);fields[key]=value;overridesText.value=JSON.stringify(fields,null,2)}
function courseField(key,value){const fields=JSON.parse(configText.value);fields[key]=value;configText.value=JSON.stringify(fields,null,2)}
const courseForm=computed(()=>{try{return {...settings.value?.defaults,...JSON.parse(configText.value)}}catch{return {}}})
const fileUrl=(p)=>`/api/projects/${project.value.id}/files/${p.split('/').map(encodeURIComponent).join('/')}`
async function api(path,options={}){ const response=await fetch('/api'+path,{...options,headers:options.body instanceof FormData?{}:{'Content-Type':'application/json'},credentials:'same-origin'}); const data=await response.json(); if(!response.ok) throw new Error(data.error?.message||data.detail||'操作失败'); return data }
async function act(fn){busy.value=true;error.value='';notice.value='';try{return await fn()}catch(e){error.value=String(e.message)}finally{busy.value=false}}
async function login(){await act(async()=>{await api('/session',{method:'POST',body:JSON.stringify({token:token.value})}); token.value='';history.replaceState(null,'',location.pathname+location.search);logged.value=true;settings.value=await api('/settings');await refreshList()})}
async function refreshList(){projects.value=await api('/projects')}
function loadEditor(){dirty.value=false;checksDirty.value=false;const v=version.value;display.value=v?.raw_display||'';reading.value=v?.raw_reading||'';checks.value=JSON.parse(JSON.stringify(v?.checks||{knowledge_points:[],questions:[],terms:[],pending:[]}));reviewNote.value='';listenNote.value='';listenChecks.value={timbre:false,pronunciation:false,no_omission:false,no_repetition:false};overridesText.value=JSON.stringify(scene.value?.overrides||{},null,2)}
async function open(p){await act(async()=>{await flushSave();project.value=await api(`/projects/${p.id}`);selected.value=project.value.scenes.find(s=>!s.skipped)?.id||project.value.scenes[0]?.id||'';configText.value=JSON.stringify(project.value.config,null,2);tab.value=project.value.slides.length?'workbench':'assets';report.value=null;snapshot.value=null;loadEditor();await refreshJobs()})}
async function create(){await act(async()=>{const p=await api('/projects',{method:'POST',body:JSON.stringify({name:name.value})});name.value='';await refreshList();project.value=p;tab.value='assets';configText.value=JSON.stringify(p.config,null,2)})}
async function refreshProject(){if(!project.value)return; project.value=await api(`/projects/${project.value.id}`);if(!project.value.scenes.some(s=>s.id===selected.value&&(showSkipped.value||!s.skipped))) selected.value=project.value.scenes.find(s=>!s.skipped)?.id||project.value.scenes[0]?.id||''}
async function command(action,data){project.value=await api(`/projects/${project.value.id}/commands`,{method:'POST',body:JSON.stringify({revision:project.value.revision,action,data})});report.value=null;snapshot.value=null}
let debounce, savePromise=null
function edit(){dirty.value=true; clearTimeout(debounce);debounce=setTimeout(()=>flushSave().catch(e=>error.value=e.message),900)}
async function flushScript(){clearTimeout(debounce);if(savePromise)await savePromise;if(!dirty.value||!scene.value)return; const sid=scene.value.id, d=display.value,r=reading.value; saving.value=true;savePromise=command('script',{scene_id:sid,display_text:d,reading_text:r});try{await savePromise;dirty.value=display.value!==d||reading.value!==r;notice.value='已自动保存';}finally{saving.value=false;savePromise=null}}
async function flushSave(){await flushScript();if(checksDirty.value&&scene.value&&!scene.value.confirmed){await command('checks',{scene_id:scene.value.id,checks:checks.value});checksDirty.value=false}}
async function selectScene(id){await act(async()=>{await flushSave();selected.value=id;loadEditor()})}
async function upload(role,event){const file=event.target.files[0];if(!file)return;await act(async()=>{await flushSave();const form=new FormData();form.set('file',file);form.set('authorization',rights.value);form.set('teacher_id',teacher.value);form.set('revision',project.value.revision);await api(`/projects/${project.value.id}/assets/${role}`,{method:'POST',body:form});await refreshProject();await refreshJobs();notice.value='素材处理已排队，状态来自实际任务'});event.target.value=''}
async function selectAsset(role){await act(async()=>{await api(`/projects/${project.value.id}/assets/${role}/selection`,{method:'POST',body:JSON.stringify({revision:project.value.revision,selection:JSON.parse(selections.value[role])})});await refreshProject();await refreshJobs()})}
async function scriptMode(mode){await act(async()=>{await flushSave();if(mode==='ai'){await api(`/projects/${project.value.id}/scenes/${scene.value.id}/ai`,{method:'POST',body:JSON.stringify({revision:project.value.revision})});await refreshJobs()}else{await command('notes',{scene_id:scene.value.id});loadEditor()}})}
async function approve(){await act(async()=>{await flushSave();await command('review',{scene_id:scene.value.id,checks:checks.value,note:reviewNote.value});loadEditor();notice.value='教师审核版本已锁定'})}
async function audition(){await act(async()=>{await flushSave();await api(`/projects/${project.value.id}/scenes/${scene.value.id}/audition`,{method:'POST',body:JSON.stringify({revision:project.value.revision})});await refreshJobs()})}
async function listenReview(){await act(async()=>{await command('listen_review',{scene_id:scene.value.id,checks:listenChecks.value,note:listenNote.value});notice.value='试听核查已记录'})}
async function applyConfig(all=false,reset=false){await act(async()=>{await flushSave();await command('page_config',{scene_ids:all?(chosen.value.length?chosen.value:project.value.scenes.map(s=>s.id)):[scene.value.id],overrides:reset?{}:JSON.parse(overridesText.value),replace:reset});loadEditor()})}
async function reorder(delta){await act(async()=>{await flushSave();const ids=project.value.scenes.map(s=>s.id),i=ids.indexOf(selected.value),j=i+delta;if(j<0||j>=ids.length)return;[ids[i],ids[j]]=[ids[j],ids[i]];await command('structure',{action:'reorder',scene_ids:ids})})}
async function merge(){await act(async()=>{await flushSave();await command('structure',{action:'merge',scene_ids:project.value.scenes.filter(s=>chosen.value.includes(s.id)).map(s=>s.id)});chosen.value=[];selected.value=project.value.scenes[0]?.id;loadEditor()})}
const splitText=ref('')
async function split(){await act(async()=>{await flushSave();await command('structure',{action:'split',scene_id:scene.value.id,parts:splitText.value.split('\n---\n')});selected.value=project.value.scenes[0]?.id;loadEditor()})}
async function preflight(){await act(async()=>{await flushSave();report.value=await api(`/projects/${project.value.id}/preflight`,{method:'POST'})})}
async function freeze(){await act(async()=>{await flushSave();snapshot.value=await api(`/projects/${project.value.id}/snapshots`,{method:'POST',body:JSON.stringify({revision:project.value.revision})});notice.value='已创建不可变审核快照，可进入视频与成果'})}
function download(value,filename){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=filename;a.click();URL.revokeObjectURL(url)}
async function refreshJobs(){if(project.value)jobs.value=await api(`/projects/${project.value.id}/jobs`)}
let polling,pollDisconnected=false
async function handleLaunchHash(){const launch=new URLSearchParams(location.hash.slice(1)).get('launch');if(!launch)return;history.replaceState(null,'',location.pathname+location.search);await act(async()=>{await api('/session/launch',{method:'POST',body:JSON.stringify({ticket:launch})});logged.value=true;settings.value=await api('/settings');if(!project.value)await refreshList()})}
window.addEventListener('hashchange',handleLaunchHash)
onMounted(async()=>{const queryProject=new URLSearchParams(location.search).get("project");const remembered=queryProject?{id:queryProject,tab:"workbench"}:JSON.parse(sessionStorage.getItem('mooc-workbench')||'null');const hash=new URLSearchParams(location.hash.slice(1)),launch=hash.get('launch');token.value=hash.get('token')||'';history.replaceState(null,'',location.pathname+location.search);if(launch)await act(async()=>{await api('/session/launch',{method:'POST',body:JSON.stringify({ticket:launch})});logged.value=true;settings.value=await api('/settings');await refreshList()});else if(token.value)await login();else await act(async()=>{settings.value=await api('/settings');logged.value=true;await refreshList()});if(logged.value&&remembered&&projects.value.some(p=>p.id===remembered.id)){await open({id:remembered.id});if(['assets','workbench','listen','preflight','m1review','media'].includes(remembered.tab))tab.value=remembered.tab;if(project.value.scenes.some(s=>s.id===remembered.selected&&!s.skipped))selected.value=remembered.selected;loadEditor()}polling=setInterval(async()=>{if(!project.value||busy.value||saving.value)return;try{const before=JSON.stringify(jobs.value);await refreshJobs();if(pollDisconnected){error.value='';pollDisconnected=false}if(before!==JSON.stringify(jobs.value)&&!dirty.value&&!checksDirty.value){const old=version.value?.id;await refreshProject();if(old!==version.value?.id)loadEditor()}}catch(e){pollDisconnected=true;error.value=e.message}},2000)})
onUnmounted(()=>{clearInterval(polling);clearTimeout(debounce);window.removeEventListener('hashchange',handleLaunchHash)})
</script>

<template>
<div><a class="advanced-back" :href="project ? `/?project=${project.id}` : `/`">← 返回一键慕课制作</a></div><div class="app-shell">
  <aside class="rail"><div class="brand">慕<span>课</span></div><div class="rail-label">教师内容工作台</div><button @click="act(async()=>{await flushSave();project=null;await refreshList()})">课程项目</button><div class="rail-bottom">M3 · 内容与视频<br>本机受控存储<br>素材不用于训练</div></aside>
  <main>
    <header><div><div class="eyebrow">DIGITAL TEACHER / COURSE</div><h1>{{ project?.name || '课程项目' }}</h1></div><span class="badge">{{ saving?'保存中':project?'版本 '+project.revision:'本地工作台' }}</span></header>
    <div v-if="error" class="alert error" role="alert">{{error}} <button @click="error=''">关闭</button></div><div v-if="notice" class="alert">{{notice}}</div>
    <section v-if="!logged" class="panel"><h2>本地访问</h2><p>输入启动器显示的访问令牌。</p><input v-model="token" type="password" aria-label="访问令牌"><button @click="login">登录</button></section>
    <template v-else-if="!project">
      <section class="panel create-row"><div><h2>准备下一堂课</h2><p>从原始课件开始，逐页编辑、核查与试听。</p></div><input v-model="name" placeholder="课程名称" aria-label="课程名称"><button class="primary" @click="create" :disabled="busy||!name.trim()">新建课程</button></section>
      <div class="project-grid"><section v-for="p in courseProjects" :key="p.id" class="panel project-card"><span class="eyebrow">课程 / {{zh(p.state)}}</span><h2>{{p.name}}</h2><p>{{new Date(p.updated_at).toLocaleString('zh-CN')}}</p><p v-if="p.source_project_id">副本 · 保留来源关系</p><div class="actions"><button class="primary" @click="open(p)">继续制作</button><details class="more"><summary>更多</summary><button @click="act(async()=>{await api(`/projects/${p.id}/copy`,{method:'POST'});await refreshList()})">复制</button><button @click="act(async()=>{if(confirm('删除该项目、素材副本、试听、任务和快照？其他项目的独立副本保留。')){await api(`/projects/${p.id}`,{method:'DELETE'});await refreshList()}})">删除</button><button @click="act(async()=>{const full=await api(`/projects/${p.id}`);await api(`/projects/${p.id}/commands`,{method:'POST',body:JSON.stringify({revision:full.revision,action:'category',data:{category:'development'}})});await refreshList()})">移到开发测试</button></details></div></section></div>
      <details class="panel"><summary>开发测试项目 · {{devProjects.length}} 个（保留原项目与证据）</summary><div class="project-grid"><section v-for="p in devProjects" :key="p.id" class="panel"><h2>{{p.name}}</h2><p>{{zh(p.state)}}</p><button @click="open(p)">继续查看测试项目</button><button @click="act(async()=>{const full=await api(`/projects/${p.id}`);await api(`/projects/${p.id}/commands`,{method:'POST',body:JSON.stringify({revision:full.revision,action:'category',data:{category:'course'}})});await refreshList()})">移到课程列表</button></section></div></details>
      <p v-if="!projects.length" class="empty">暂无课程。新建项目后上传课件、参考语音和教师形象。</p>
    </template>
    <template v-else>
      <div v-if="project.engineering_only" class="alert">工程验证项目：讲稿、试听与视频用于工程检查，未审核预览不计正式通过。原页与教学内容的对应关系、课程审核和人工视听质量仍待教师确认。</div>
      <nav><button :class="{active:tab==='assets'}" @click="tab='assets'">01 上传素材</button><button :class="{active:tab==='workbench'}" @click="tab='workbench'">02 生成并审核讲稿</button><button :class="{active:tab==='listen'}" @click="tab='listen'">03 试听</button><button :class="{active:tab==='preflight'}" @click="tab='preflight'">04 生成前检查</button><button :class="{active:tab==='m1review'}" @click="tab='m1review'">05 人物与音色评审</button><button :class="{active:tab==='media'}" @click="tab='media'">06 视频与成果</button></nav>
      <M1Review v-if="tab==='m1review'" :key="project.id" :project="project" :api="api"/><MediaWorkbench v-if="tab==='media'" :key="project.id" :project="project" :selected="selected" :api="api"/><section v-if="tab==='assets'"><CloudPhotoSettings :project="project" :disabled="busy||jobs.some(j=>['queued','running'].includes(j.state))" @updated="p=>{project=p;refreshProject()}"/>
        <div class="panel"><h2>素材权利与教师映射</h2><p>参考语音用于教师音色；形象使用照片或视频。填写处理授权记录，三类人物素材须关联同一教师。</p><label>权利确认记录<input v-model="rights" placeholder="来源、同意记录、允许本地处理范围"></label><label>教师标识<input v-model="teacher" placeholder="例如 teacher-001"></label><p>上限：课件 {{settings?.limits_mb.pptx}} MB / {{settings?.max_ppt_pages}} 页，照片 20 MB，视频 500 MB，语音 50 MB；准确容量以服务器配置为准。</p></div>
        <div class="asset-grid"><section v-for="role in ['pptx','reference_audio','photo','video']" :key="role" class="panel"><h2>{{roleNames[role]}}</h2><p>{{project.assets[role]?.filename||'尚未上传'}} · {{zh(project.assets[role]?.state)||'待准备'}}</p><input type="file" :aria-label="roleNames[role]" :accept="{pptx:'.pptx,.ppt',reference_audio:'.wav,.mp3,.m4a',photo:'.png,.jpg,.jpeg',video:'.mp4'}[role]" @change="upload(role,$event)" :disabled="busy||!rights.trim()||(role!=='pptx'&&!teacher.trim())"><p v-for="w in project.assets[role]?.warnings" class="warning">{{w}}</p><p v-if="project.assets[role]?.error" class="warning">{{project.assets[role].error.message}}</p>
          <template v-if="project.assets[role]?.state==='ready'"><img v-if="role==='photo'" class="asset-preview" :src="fileUrl(project.assets[role].selected)" alt="已选教师照片"><video v-if="role==='video'" controls class="asset-preview" :src="fileUrl(project.assets[role].selected)"></video><audio v-if="role==='reference_audio'" controls :src="fileUrl(project.assets[role].selected)"></audio><p v-if="role==='pptx'">{{project.slides.length}} 页 · 结构与原页分别保存</p><template v-else><label>{{role==='photo'?'裁剪坐标（左、上、右、下）':'显式片段选取（秒）'}}<AssetSelection :role="role" v-model="selections[role]"/></label><button @click="selectAsset(role)">{{role==='photo'?'应用裁剪':'应用片段选取'}}</button><p class="hint">{{role==='reference_audio'?'原件保留。GPT v2 参考片段为 3–10 秒，请填写准确对应文字。':role==='video'?'片段为 5–60 秒。预览使用实际视频序列。':'原件保留，裁剪只创建派生素材。'}}</p></template></template>
        </section></div>
        <details class="panel"><summary>课程设置 · 自动继承到页面</summary><div class="form-grid"><label>课程名<input :value="courseForm.course_name" @input="courseField('course_name',$event.target.value)"></label><label>章节<input :value="courseForm.chapter" @input="courseField('chapter',$event.target.value)"></label><label>目标受众<input :value="courseForm.audience" @input="courseField('audience',$event.target.value)"></label><label>讲解详略<select :value="courseForm.detail" @change="courseField('detail',$event.target.value)"><option>简略</option><option>标准</option><option>详细</option></select></label><label>每页目标秒数<input type="number" :value="courseForm.target_seconds" @input="courseField('target_seconds',Number($event.target.value))"></label><label>教师形象模式<select :value="courseForm.mode" @change="courseField('mode',$event.target.value)"><option value="photo">照片</option><option value="video">视频序列</option></select></label><label>画质<select :value="courseForm.resolution" @change="courseField('resolution',$event.target.value)"><option>720p</option><option>1080p</option></select></label><label><input type="checkbox" :checked="courseForm.subtitles" @change="courseField('subtitles',$event.target.checked)">显示字幕</label></div><details><summary>全课高级配置与术语表</summary><textarea v-model="configText" rows="15" aria-label="课程设置"></textarea></details><button @click="act(async()=>{await command('config',JSON.parse(configText));notice='课程设置已保存'})">保存课程设置</button></details>
      </section>
      <section v-if="tab==='workbench'||tab==='listen'">
        <div class="panel"><h2>{{tab==='listen'?'逐页试听':'全课讲稿与审核进度'}}</h2><p>活动片段 {{activeScenes.length}} · 已确认 {{activeScenes.filter(s=>s.confirmed).length}} · 理解问题 {{questionCount}} / 至少 5 问</p><p v-if="project.formal_scope&&!project.engineering_only">正式课时：第 {{project.formal_scope.first}}–{{project.formal_scope.last}} 页 · {{project.formal_scope.title}}。教师审核仍由你逐页完成。</p><div class="actions"><button class="primary" @click="batchAI()" :disabled="busy||!settings?.ai.ready||!!aiCounts.queued||!!aiCounts.running">生成当前课时逐页讲稿（{{activeScenes.length}} 段）</button><button @click="batchAI(true)" :disabled="busy||!aiCounts.failed">重试失败页（{{aiCounts.failed||0}}）</button></div><p v-if="latestAI.length">AI 任务：已完成 {{aiCounts.completed}} · 处理中 {{aiCounts.running}} · 排队 {{aiCounts.queued}} · 失败 {{aiCounts.failed}}</p><p class="hint">AI 草稿需要教师核查；人工稿保留为当前稿，AI 新稿以候选版本保存。完成审核后，可在视频与成果中生成真实样片和整课。</p></div>
        <details v-if="project.review_items" class="panel"><summary>本课时审核参考清单 · {{project.review_items.reduce((n,p)=>n+p.items.length,0)}} 项</summary><p>请逐页核对数字、单位、读法、答案来源和完整试听，并在右侧记录审核决定。以下是生成时的核查线索。</p><a :href="fileUrl(project.review_packet)" download>下载教师审核清单（Markdown）</a><section v-for="p in project.review_items" :key="p.source_index"><h3>原页 {{p.source_index}}</h3><ul><li v-for="item in p.items">{{item}}</li></ul><button @click="selectScene(project.scenes.find(s=>s.source_page_ids.includes(project.slides.find(x=>x.source_index===p.source_index).source_page_id)).id)">打开此页审核</button></section></details><div class="workbench" v-if="project.scenes.length">
          <aside class="panel scene-list"><h2>讲解结构 <small>{{project.scenes.length}} 段</small></h2><p class="hint">勾选相邻片段可合并或批量应用设置。</p><label><input type="checkbox" v-model="showSkipped">显示课时外已跳过页</label><div v-for="(s,i) in visibleScenes" :key="s.id" class="scene-row" :class="{selected:s.id===selected}"><input type="checkbox" :value="s.id" v-model="chosen" aria-label="选择批量范围"><button @click="selectScene(s.id)"><strong>{{String(i+1).padStart(2,'0')}} · 原页 {{s.source_page_ids.map(id=>project.slides.find(p=>p.source_page_id===id)?.source_index).join('、')}}</strong><span>{{s.skipped?'已跳过':s.confirmed?'已确认':'待审核'}} · {{zh(s.kind)}}</span></button></div><div class="actions"><button @click="reorder(-1)">上移</button><button @click="reorder(1)">下移</button><button @click="merge">合并选中</button></div></aside>
          <section class="panel original"><div class="section-title"><h2>原课件</h2><span class="badge">第 {{slide?.source_index}} 页</span></div><div class="slide-preview"><img v-if="slide" :src="fileUrl(slide.image)" alt="原始课件页面"><div v-if="scene?.effective_config.show_teacher" class="teacher-placeholder" :class="scene.effective_config.position" :style="{width:scene.effective_config.size*100+'%'}"><img v-if="project.assets.photo&&project.config.mode!=='video'" :src="fileUrl(project.assets.photo.selected)" alt="布局中的教师照片"><span v-else>教师区域</span></div></div><p class="hint">布局预览 · {{scene?.effective_config.show_teacher?'显示人物':'隐藏人物，保留讲解与字幕'}}。原课件保留，不重画。</p><select :value="scene.play_page_id" @change="act(async()=>{await command('structure',{action:'play_page',scene_id:scene.id,source_page_id:$event.target.value})})" aria-label="播放原页"><option v-for="id in scene.source_page_ids" :value="id">原页 {{project.slides.find(s=>s.source_page_id===id)?.source_index}}</option></select><details><summary>正文、备注与异常标记</summary><h3>正文</h3><pre>{{slide?.body}}</pre><h3>原备注</h3><pre>{{slide?.notes_original||'无备注'}}</pre><ul><li v-for="a in slide?.anomalies">{{a.code}}</li></ul><p class="hint">稳定来源 {{slide?.source_page_id}}</p></details><div class="actions"><button @click="act(async()=>{await command('structure',{action:'skip',scene_id:scene.id,skipped:!scene.skipped})})">{{scene.skipped?'恢复讲解':'跳过讲解'}}</button><select :value="scene.kind" @change="act(async()=>{await command('structure',{action:'plan',scene_id:scene.id,kind:$event.target.value})})" aria-label="讲解用途"><option value="intro">导入</option><option value="lecture">讲解</option><option value="transition">过渡</option><option value="summary">总结</option></select></div><details><summary>拆分当前片段</summary><p>片段之间用独立一行 --- 分隔；每段保留当前原页映射。</p><textarea v-model="splitText" rows="6"></textarea><button @click="split">拆分</button></details></section>
          <section class="panel editor"><div class="section-title"><h2>逐页讲稿</h2><span class="badge">{{zh(version?.mode)||'未编写'}} · v{{version?.number||0}}</span></div><div class="actions"><button @click="scriptMode('ai')">AI 生成新版本</button><button @click="scriptMode('notes')">使用备注原文</button></div><div v-if="candidate" class="alert">AI 新稿已生成，当前人工稿保留。<details><summary>预览 AI 候选稿</summary><p>{{candidate.display_text}}</p></details><button @click="act(async()=>{await flushSave();await command('adopt_ai',{scene_id:scene.id,version_id:candidate.id});loadEditor()})">采用 AI 候选为新版本</button></div><p v-if="!settings?.ai.ready" class="hint">AI 服务待配置；原文、外部稿和编辑可独立使用。</p><div v-if="version?.teaching_check_state==='pending'" class="alert" role="status">讲稿正文已保存，教学核查尚未完成。<p v-if="version.teaching_check_error" class="warning">{{version.teaching_check_error.message}}</p><button @click="retryTeaching" :disabled="busy||jobs.some(j=>['queued','running'].includes(j.state))">仅重试教学核查</button><p>也可填写完整核查表并保存，再由教师确认。</p></div><label>显示稿<textarea v-model="display" @input="edit" rows="7" aria-label="显示稿"></textarea></label><label>读法稿<textarea v-model="reading" @input="edit" rows="7" aria-label="读法稿"></textarea></label><p class="hint">停顿语法：<code v-pre>{{pause:1.0}}</code>。区间 [0,1]、数组 [1,2,3] 和引用 [1] 会保留。</p><button @click="act(flushSave)">立即保存</button><details><summary>版本与来源</summary><p v-for="v in scene.versions" :key="v.id">v{{v.number}} · {{zh(v.mode)}} · {{v.teacher_review?'已锁定':'草稿'}} <button @click="act(async()=>{await flushSave();await command('rollback',{scene_id:scene.id,version_id:v.id});loadEditor()})">回退为新版本</button></p><pre>{{version?.provenance}}</pre></details><details open><summary>教师核查与确认</summary><p class="hint">核查原页和讲稿，填写知识点、读法、问题与来源。正式课时至少 5 问。</p><ReviewForm :checks="checks" :pages="project.slides.filter(p=>scene.source_page_ids.includes(p.source_page_id))" :locked="!!scene.confirmed" @change="checksDirty=true"/><button @click="applyReviewedTerms" :disabled="busy||!!scene.confirmed||!checks.terms.length||checks.terms.some(t=>!t.text.trim()||!t.reading.trim())">将核查读法应用到当前页</button><details><summary>实际朗读文本与停顿</summary><pre>{{version?.reading_text}}</pre><p v-for="e in version?.control_events">字符位置 {{e.offset}} · 停顿 {{e.seconds}} 秒</p></details><button @click="saveChecks" :disabled="busy||!version||!!scene.confirmed">保存核查草稿</button><label>教师核查记录<input v-model="reviewNote" placeholder="说明核对、修订与待确认项处理结果" aria-label="教师核查记录"></label><button class="primary" @click="approve" :disabled="busy||!!scene.confirmed||!reviewNote.trim()||checks.pending.length>0">{{scene.confirmed?'当前版本已确认':'我已审核，确认当前版本'}}</button></details>
          <details><summary>逐页设置与继承</summary><div class="form-grid"><label><input type="checkbox" :checked="pageForm.show_teacher" @change="overrideField('show_teacher',$event.target.checked)">显示教师人物</label><label>布局方式<select :value="pageForm.layout" @change="overrideField('layout',$event.target.value)"><option value="overlay">小窗</option><option value="sidebar">侧栏（课件预留空间）</option></select></label><label>人物位置<select :value="pageForm.position" @change="overrideField('position',$event.target.value)"><option value="bottom-right">右下</option><option value="bottom-left">左下</option><option value="top-right">右上</option><option value="top-left">左上</option></select></label><label>人物尺寸比例<input aria-label="人物尺寸比例" type="number" min="0.1" max="0.6" step="0.05" :value="pageForm.size" @input="overrideField('size',Number($event.target.value))"></label><label>语速倍率<input aria-label="语速倍率" type="number" min="0.5" max="2" step="0.1" :value="pageForm.speed" @input="overrideField('speed',Number($event.target.value))"></label><label>讲解前停顿（秒）<input type="number" min="0" max="10" step="0.1" :value="pageForm.pause_before" @input="overrideField('pause_before',Number($event.target.value))"></label><label>讲解后停顿（秒）<input type="number" min="0" max="10" step="0.1" :value="pageForm.pause_after" @input="overrideField('pause_after',Number($event.target.value))"></label></div><details><summary>覆盖值与术语读法表</summary><textarea v-model="overridesText" rows="7" aria-label="逐页配置"></textarea></details><div class="actions"><button @click="applyConfig()">应用当前页</button><button @click="applyConfig(true)">应用 {{chosen.length||project.scenes.length}} 段</button><button @click="applyConfig(false,true)">恢复继承</button></div><pre>{{scene.config_sources}}</pre></details><div class="audition"><button @click="preview" :disabled="busy||!version">生成草稿真实试听</button><template v-if="scene.preview_audition"><p class="warning">草稿试听 · 未审核，不计入正式内容就绪{{scene.preview_audition.version_id!==scene.current_version?' · 已过期':''}}</p><audio controls :src="fileUrl(scene.preview_audition.path)"></audio></template><button class="primary" @click="audition" :disabled="!scene.confirmed">生成真实语音试听</button><template v-if="scene.audition"><p>{{scene.audition.provider}} · {{scene.audition.duration_seconds.toFixed(2)}} 秒 · {{scene.audition.stale?'已失效':'当前版本'}} · {{scene.audition.human_review?'试听已评审':'待人工试听'}}</p><audio controls :src="fileUrl(scene.audition.path)"></audio><label><input v-model="listenNote" placeholder="试听核查记录：音色、读法、漏句、重复"></label><div class="listen-checks"><label v-for="(label,k) in {timbre:'音色一致',pronunciation:'术语与读法正确',no_omission:'无漏句',no_repetition:'无重复'}"><input type="checkbox" v-model="listenChecks[k]">{{label}}</label></div><button @click="listenReview" :disabled="!Object.values(listenChecks).every(Boolean)||!listenNote.trim()||scene.audition.stale">记录四项试听核查</button></template></div>
          </section>
        </div><div v-else class="panel empty">先上传并解析课件。</div>
        <details class="panel"><summary>外部逐页稿导入</summary><p>先下载模板，使用完整稳定原页 ID 映射。服务端阻断遗漏、重复或错位，保留字面原稿。</p><button @click="act(async()=>download(await api(`/projects/${project.id}/import-template`),'scripts-template.json'))">下载映射模板</button><input type="file" accept=".json" aria-label="外部逐页稿" @change="async e=>{importText=await e.target.files[0].text()}"><textarea v-model="importText" rows="7" aria-label="外部稿 JSON"></textarea><button @click="act(async()=>{await flushSave();await command('import',JSON.parse(importText));loadEditor()})">导入为新版本</button></details>
      </section>
      <section v-if="tab==='preflight'" class="panel"><h2>生成前检查</h2><p>检查素材、原页映射、审核版本、教学问题、当前试听及模型约束。耗时与费用缺实测基线时显示未知。</p><div class="actions"><button class="primary" @click="preflight" :disabled="busy">{{busy?'检查中':'运行预检'}}</button><button @click="freeze" :disabled="!report?.ready||busy">锁定并导出内容快照</button></div><template v-if="report"><h3>{{report.ready?'内容预检就绪':'存在阻断项'}}</h3><p>编辑时长提示 {{Math.round(report.estimated_seconds)}} 秒 · 生成耗时未知 · 生成费用未知</p><ul class="blockers"><li v-for="b in report.blockers"><strong>{{b.code}}</strong> · {{b.message}}<p>{{b.remedy}} <button @click="tab=project.scenes.some(s=>s.id===b.source)?'workbench':'assets';if(project.scenes.some(s=>s.id===b.source))selectScene(b.source)">定位修复</button></p></li></ul><p v-for="w in report.warnings" class="warning">{{w.message}}</p><details><summary>真实模型能力与健康状态</summary><pre>{{report.models}}</pre></details></template><button v-if="snapshot" @click="download(snapshot,'content-snapshot.json')">下载审核快照 JSON</button></section>
      <details v-if="jobs.length" class="panel"><summary>任务历史（含旧失败记录） · {{jobs.filter(j=>['queued','running'].includes(j.state)).length}} 项等待或运行</summary><p v-for="j in jobs" :key="j.id">{{zh(j.kind)}} · {{j.payload.scene_id?'原页 '+project.scenes.find(s=>s.id===j.payload.scene_id)?.source_page_ids.map(id=>project.slides.find(p=>p.source_page_id===id)?.source_index).join('、'):''}} · {{zh(j.state)}} / {{zh(j.stage)}} <span class="warning">{{j.error?.message}}</span><button v-if="j.kind==='ai'&&j.state==='failed'&&latestAI.find(x=>x.payload.scene_id===j.payload.scene_id)?.id===j.id" @click="act(async()=>{await flushSave();await api(`/projects/${project.id}/scenes/${j.payload.scene_id}/ai`,{method:'POST',body:JSON.stringify({revision:project.revision})});await refreshJobs()})">重试此页</button></p></details>
    </template>
  </main>
</div>
</template>



